package com.kelasdicoding.minipokedex;

import java.util.ArrayList;

public class PokeData {
    private static String[] names={
            "377",
            "378",
            "379",
            "380",
            "381",
            "382",
            "383",
            "384",
            "386",
            "486"
    };

    private static String[] type={
            "Type-1",
            "Type-2",
            "Type-3",
            "Type-1",
            "Type-2",
            "Type-3",
            "Type-1",
            "Type-2",
            "Type-3",
            "Type-1",
            "Type-2"
    };

    private static int[] photo={
            R.drawable.poke_377,
            R.drawable.poke_378,
            R.drawable.poke_379,
            R.drawable.poke_380,
            R.drawable.poke_381,
            R.drawable.poke_382,
            R.drawable.poke_383,
            R.drawable.poke_384,
            R.drawable.poke_386,
            R.drawable.poke_486
    };

    private static String[] detail={
            "Regirock is a large golem made of brown rocks. Regirock has an orange pattern on its face that resembles a capital letter \"H\". It has long arms with jutting shoulders and club-like hands, its legs are short in comparison to its body. There is a line of rocky spines running down its back. When it gets damaged in battle it will search for new rocks to repair itself. Because of this, the rocks it is made of come from several different places, which contributes to Regirock's patchwork appearance. Regirock does not seem to have a heart or brain. It generally lives in caves.\nA Regirock made a cameo appearance alongside the other members of its trio in the opening sequence of The Rise of Darkrai, where they all fired Hyper Beams that combined into an extremely powerful one.\nA Regirock briefly appeared in PK18, where it sent Meowth and his cronies blasting off after they tried to move it out of their way.\nA Regirock appeared in a flashback in Pillars of Friendship!.",
            "Regice is composed of Antarctic ice that closely resembles a crystal. Its face has an unusual pattern consisting of seven yellow dots in a \"+\" formation. It has four spikes on its back. Its legs are conical and it balances its entire body on those two points. There are three fingers on each of its cylindrical arms. In the anime, Regice moves around by floating in the air. Regice cloaks itself in air that is -328 degrees Fahrenheit, and can survive submerged in molten lava and other extremely hot temperatures. Regice slept in a glacier for thousands of years.\nA Regice made a cameo appearance alongside the other members of its trio in the opening sequence of The Rise of Darkrai, where they all fired Hyper Beams that combined into an extremely powerful one.\nA Regice briefly appeared in PK18, where it met Pikachu and Meowth's groups at the other side of an ice bridge and sent them into a lake.\nA Regice appeared in a flashback in Pillars of Friendship!.\n",
            "The top-half of Registeel's body is spherical and gray with a black stripe running down its face. Its face consists of seven red dots in a hexagonal formation. It has black arms with three fingers each and cylindrical legs. While Registeel has been classified as a Steel-type Pokémon, its body is actually made of a material that is harder than any known metal. However, this material stretches and shrinks despite its hardness. Its body was tempered by pressure underground over thousands of years.\nRegisteel debuted in a brief cameo during the opening sequence of Destiny Deoxys.\nA Registeel made a cameo appearance alongside the other members of its trio in the opening sequence of The Rise of Darkrai, where they all fired Hyper Beams that combined into an extremely powerful one.\n\nA Registeel briefly appeared in PK18, where it sent Meowth and his cronies blasting off after they mistook him for a floating Pokémon.\n\nA Registeel appeared in a flashback in Pillars of Friendship!.",
            "Latias is a Pokémon with a bird-like body stylized after a plane. Its long neck stretches forward from its squat body. It has no legs, usually floating instead. The rear half of its body is largely red and the upper half white, with jet-plane wings high on its rear and fins on the bottom near its tail. A blue triangle marks the center of its chest, while a red mask partially covers its face. Ear-like fins sit on top of its head and its eyes are yellow. It has short, three-fingered arms with a red covering on the outer side of the lower arms. Latias is a female only species, with Latios being its male counterpart.\n\nAs Mega Latias, the red parts of its body change to purple. Horns grow from the side of its head and run along its jaw. It loses the wings on its back and similar but larger wings attach to its lower arms, normally held in a level position. Triangle shapes now mark the forward point of its wings instead of its chest.\n\nLatias ruffles its feathers and cries loudly when there is hostility toward it. Its glass-like, downy feathers can enfold its body and refract light, which allows it to become invisible or alter its appearance. It can also use its down to use its signature move, Mist Ball. It is highly intelligent and can understand human speech. It is capable of using telepathy to communicate with others. In the fifth movie, Latias had the ability \"Sight Sharing\", which allowed Latias and people around it to see exactly what Latios was seeing. It normally does not make contact with humans or other Pokémon, and disappears when an enemy is nearby. It forms herds with several members, and is usually found near water.",
            "Latios is a Pokémon with a bird-like body stylized after a plane. Its body flows slowly into a thick neck, giving it a bulky appearance. It has no legs, usually floating instead. Most of its body is blue, with white areas near its arms and a white stripe on its back that extend up to its head. Jet-plane wings sit on top of its back, while two tall, jagged fins point behind it from its rear. A red triangle marks the center of its chest, while a blue mask partially covers its face. Long, ear-like fins extend from its jaws to over its head, and its eyes are red. It has three-fingered arms with a blue covering on the outer side of the lower arms. Latios is a male only species, with Latias being its female counterpart.\n\nAs Mega Latios, the blue parts of its body change to purple. Horns grow from the side of its head and run along its jaw. It loses the wings on its back and similar but larger wings attach to its lower arms, normally held in a level position. Triangle shapes now mark the forward point of its wings instead if its chest.\n\nLatios can fly faster than a jet by tucking in its arms. In the fifth movie, Latios had the ability \"Sight Sharing\" (Japanese: ゆめうつし Dream Analysis) which allowed Latias and people around it to see exactly what Latios was seeing. Oakley also mentioned that it can shape-shift. It prefers compassionate Trainers, to whom it opens its heart. It uses telepathy to detect locations and the emotions of others, and can understand human speech. It lives by the water's edge. Latios is the only known Pokémon capable of learning Luster Purge.",
            "Kyogre is a massive whale-like Pokémon with two big pectoral fins, each with four white square-shaped nails. It has a deep blue body and a white chin area with two small spikes protruding under it. Above each eye are two white, oval-shaped spots. It has red stripes around its chin, eyes, dorsal fins, and torso. These stripes glow when Kyogre is brimming with power. The tail is tattered with four trailing parts, the inner ones being smaller than the outer. Its eyes are small, yellow, and shadowed with black.\n\nPrimal Kyogre retains its general body structure, but grows to more than double the size of its base form. Its main skin color becomes a darker shade of blue, the red markings along its body become light blue, and its eyes glow yellow with orange irises and orange-red pupils. The markings on its pectoral fins slightly change to form α symbols, which connect to its outer nails with red markings connecting the inner nails. Every part of its skin that was white in its base form becomes clear and translucent, with the large ovals on its head now connected to clear markings stretching from its tail to its forehead, where another α symbol is formed. The trailing parts of its tail grow longer and gain translucent webbing, and the areas between its pectoral fin markings also become clear. The translucent parts of its body reveal organ-like structures that glow with a mysterious light; it has a large \"organ\" at the center of its body, two smaller ones aligned with the large oval markings, and two more located in its pectoral fins. In the anime, Primal Kyogre is said to have widened the seas by a large margin simply by taking a swim.\n\nKyogre is said to be a powerful Pokémon, having control over the element of water and rain. It is said to have expanded the seas, and is hailed as a savior for quenching areas of the world plagued with drought. Kyogre is normally calm and peaceful, but if it meets its rival, Groudon, Kyogre will engage in a cataclysmic battle against it. In the Mystery Dungeon series and core series, Kyogre is able to fly. Kyogre generally lives deep in the ocean, and is said to rest in a deep trench. Kyogre is the only known Pokémon capable of learning the move Origin Pulse.",
            "Groudon is a massive, bipedal, dinosaur-like creature covered in red, segmented plates of thick skin that act as armor. It has a gray underside and large white spikes that run along the sides of its head, body, and tail. It has four claws on each hand, four dozer-like blades on the end of its large tail, and three claws on each foot with gray markings under its feet. It also has blue stripes inside the seams of its armor plating which can only be seen when Groudon is glowing with power.\n\nAs Primal Groudon, its appearance is similar to Groudon, but larger in size. Its skin color changes from dark red to deep crimson with its underside, spikes, and teeth turning black. The blades on its tail are more separated from one another. The Ω symbol is now shown on its arms. Its eyes, the inside of its mouth, and the now-enlarged openings between its armor plating glow bright yellow, and its irises are now red. The energy that fills Primal Groudon pours forth as magma, and it burns with such an extreme temperature that its body is always shimmering with the haze of its heat.[1] In the anime, Primal Groudon is said to create new land with every step it takes.\n\nGroudon is an immensely powerful Pokémon, having the ability to summon intense droughts and cause volcanic eruptions. The droughts it can cause allow it to evaporate water, while the volcanic eruptions it can summon enable it to create land. It sleeps underground in large magma chambers. If it encounters its rival, Kyogre, they will engage in a cataclysmic battle. Groudon is the only known Pokémon capable of learning the move Precipice Blades.",
            "Rayquaza is a large, green, serpentine creature. It has red-tipped, rudder-like wings on its shoulders and down its body, and similarly patterned fins on the tip of its tail. Yellow ring-like symbols run across the length of Rayquaza's body and it has an additional yellow ring on top of its head. Rayquaza has two limbs with three-clawed hands, and two long, flat, horn-like structures on its head, with two shorter horns along its jawline. It has small, yellow eyes with black pupils, prominent pink gums, and two discernible fangs in its upper jaw.\n\nAs Mega Rayquaza, its body becomes longer and gains more features. Its head becomes longer with the Δ symbol appearing on its forehead. Its eyes now contain yellow pupils and red irises, and black, tree-like markings trail behind its eyes. Its red lips and teeth become gold, and the gold lines connect to those on its lower horns, which take on a broad, triangular shape. At the outer edges of its lower horns are long, golden, glowing tendrils that each extend to a green, fin-like structure; these tendrils have ring patterns that strongly resemble the yellow markings running along the length of Rayquaza's normal form. Its two upper horns become longer with a gold line running over them in a V shape, and each upper horn has another glowing tendril that ends in a circular shape with a spike. Along the length of its body are golden, glowing orbs placed where its ring patterns used to be. The chin, part of the neck, and parts of its serpentine body are changed to the color black. The fins running along its body are now marked with gold lines; the fins on its tail become entirely yellow and substantially longer. Particles stream from the long tendrils that extend from its jutting jaw; these particles can control the density and humidity of the air, allowing Mega Rayquaza to manipulate the weather. Its green hide sparkles with an emerald-like quality.[1]\n\nInside Rayquaza's body lies an organ that contains the same power as a Mega Stone. A Devon Corporation scientist named this organ the mikado organ (Japanese: ミカド器官). By consuming meteoroids as it flies through the stratosphere, the mikado organ will be filled with enough energy to enable Rayquaza's Mega Evolution.\n\nIt is able to soothe the other members of the weather trio, even in their Primal Forms. Rayquaza is said to have lived for hundreds of millions of years in the ozone layer, where it feeds on water and other particles. Rayquaza is rarely seen by people; even in flight, its appearance is indistinguishable from that of a meteor. Rayquaza preys on the Minior in the Alola region. Rayquaza is the only known Pokémon capable of learning the move Dragon Ascent.",
            "Deoxys is an alien-like bipedal Pokémon that has four Formes, each focused on a different stat. The main components that are constant for all four Formes are a dominant reddish orange color, a bluish-green face, and three bluish-green dots on its back arranged in a triangle. Typically, there is a purple stripe running down the center of its face and a purple, crystalline organ in its chest. Its white, circular eyes are set inside rectangular, black eye sockets. It is shown in the anime, that Deoxys may have a green crystalline organ and facial stripe.\n\nIn its Normal Forme, Deoxys has tapering legs with a segmented, vertical, blue stripe on the upper portion. The abdomen is black with vertical lines, while the majority of its skin is reddish-orange. The arms are capable of taking different forms, usually a pair of tentacles coiled in a double helix. One tentacle is the primary skin color, while the other is light blue. Alternately, it can form more humanoid arms with a red top and blue underside and a five-fingered hand. This Forme has a blunt protrusion with a single blue stripe on either side of its head and stubby tail",
            "Deoxys is an alien-like bipedal Pokémon that has four Formes, each focused on a different stat. The main components that are constant for all four Formes are a dominant reddish orange color, a bluish-green face, and three bluish-green dots on its back arranged in a triangle. Typically, there is a purple stripe running down the center of its face and a purple, crystalline organ in its chest. Its white, circular eyes are set inside rectangular, black eye sockets. It is shown in the anime, that Deoxys may have a green crystalline organ and facial stripe.\n\nIn its Normal Forme, Deoxys has tapering legs with a segmented, vertical, blue stripe on the upper portion. The abdomen is black with vertical lines, while the majority of its skin is reddish-orange. The arms are capable of taking different forms, usually a pair of tentacles coiled in a double helix. One tentacle is the primary skin color, while the other is light blue. Alternately, it can form more humanoid arms with a red top and blue underside and a five-fingered hand. This Forme has a blunt protrusion with a single blue stripe on either side of its head and stubby tail"
    };

    static ArrayList<Poke> getListData(){

        ArrayList<Poke> list = new ArrayList<>();

        for(int i=0; i<names.length;i++){
            Poke poke = new Poke();
            poke.setName(names[i]);
            poke.setPhoto(photo[i]);
            poke.setType(type[i]);
            poke.setDetail(detail[i]);
            list.add(poke);
        }
        return list;
    }
}
